name: Windows Electron Build

on: push

jobs:
  build-win:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npx @electron/packager ./ --platform=win32 --out=dist/
      - uses: actions/upload-artifact@v4
        with:
          name: subtimer
          path: dist
